services:
  server:
    image: docker.io/lucaslorentz/caddy-docker-proxy:2.10.0@sha256:a255f6712f0e576f90d2a1919fc930783121e0ac5c7767a562ad12c480c5ac20
    volumes:
      - type: bind
        source: /run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false
      - server-data:/data
      - server-config:/config
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - CADDY_DOCKER_SCAN_STOPPED_CONTAINERS=1
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
  server-config: null
