package:
  description: >
    Reverse proxy for web services, and configuration of it using Docker container image labels
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: MIT
  sources:
    - https://github.com/lucaslorentz/caddy-docker-proxy

deployment:
  compose-files:
    - deployment.compose.yml
  requires:
    filesets:
      - description: Docker socket
        paths:
          - /run/docker.sock

features:
  service-proxy:
    description: Provides reverse-proxying access to Docker Swarm services defined by other packages
    compose-files:
      - service-proxy.compose.yml
    provides:
      networks:
        - description: Bridge network for Caddy to connect to upstream services
          name: caddy-ingress
      listeners:
        - description: Web server for all HTTP requests
          port: 80
          protocol: tcp
        - description: Web server for all HTTPS requests
          port: 443
          protocol: tcp
      services:
        - description: Web server which reverse-proxies web services on the machine
          tags: [caddy-docker-proxy]
          port: 80
          protocol: http
        - description: >
            Reverse-proxy web server which provides TLS termination to web services on the machine
          tags: [caddy-docker-proxy]
          port: 443
          protocol: https
  firewall-allow-direct:
    description:
      Firewall configuration to allow accessing the reverse proxy from directly-connected devices
    requires:
      filesets:
        - description: Drop-in directory for XML fragment files to generate the nm-shared zone definition
          tags:
            - drop-in-assembly
          paths:
            - /etc/firewalld/zones.d/nm-shared
    provides:
      file-exports:
        - description: Drop-in XML fragment for firewalld's HTTP & HTTPS services
          target: overlays/etc/firewalld/zones.d/nm-shared/60-service-http.xml
  firewall-allow-public:
    description:
      Firewall configuration to allow public access to the reverse proxy
    requires:
      filesets:
        - description: Drop-in directory for XML fragment files to generate the public zone definition
          tags:
            - drop-in-assembly
          paths:
            - /etc/firewalld/zones.d/public
    provides:
      file-exports:
        - description: Drop-in XML fragment for firewalld's HTTP & HTTPS services
          target: overlays/etc/firewalld/zones.d/public/60-service-http.xml
