#!/bin/bash -eu

origins="$(cat /etc/cockpit/origins.d/* | sed 's~#.*$~~g' | sed '/^$/d' | paste -s -d ' ')"
mkdir -p /run/overlays/generated/etc/cockpit/cockpit.conf.d
echo "Origins = $origins" > /run/overlays/generated/etc/cockpit/cockpit.conf.d/20-webservice-50-origins.conf
