modifiers:
  - target: /deployments/host/docker.deploy.yml
  - target: /deployments/host/machine-name.deploy.yml
  - target: /deployments/host/sshd.deploy.yml
  - target: /deployments/host/networking
  - type: remove
    target: /deployments/host/networking
    only-matching-any:
      - avahi-cname.deploy.yml
