services:
  server:
    networks:
      - caddy-ingress
    environment:
      - FB_PORT=80 # for some reason filebrowser doesn't work if this is port 8080
      - FB_BASEURL=/admin/fs
      - FB_NOAUTH=true
    labels:
      caddy: :80
      caddy.redir: /admin/fs /admin/fs/
      caddy.handle: /admin/fs/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy-ingress:
    external: true
