package:
  description: Docker container runtime ambiently provided by the OS
  maintainers:
    - name: Ethan Li
      email: lietk12@gmail.com
  license: Apache-2.0
  sources:
    - https://github.com/moby/moby

host:
  provides:
    filesets:
      - description: Sockets for Docker and containerd
        paths:
          - /run/docker.sock
          - /var/run/docker.sock
          - /run/containerd/containerd.sock
          - /var/run/containerd/containerd.sock
      - description: systemd socket for Docker
        paths:
          - /usr/lib/systemd/system/docker.socket
      - description: Docker daemon binary
        paths:
          - /usr/bin/dockerd

features:
  start-before-network-online:
    description:
      Override the default system-provided docker.service to remove an ordering dependency for it to
      start after network-online.target
    provides:
      file-exports:
        - description: Override of the default system-provided docker.service
          target: overlays/usr/lib/systemd/system/docker.service
  firewall-zone:
    # Note: this feature is a workaround for an error Docker/Firewalld encounters in making the
    # `docker` zone on bookworm; the error doesn't occur on bullseye.
    description: Firewall configuration to support integration between Docker bridge networks and firewalld
    provides:
      file-exports:
        - description: Firewalld zone definition
          target: overlays/etc/firewalld/zones/docker.xml
        - description: Firewalld policy
          target: overlays/etc/firewalld/policies/docker-forwarding.xml
