services:
  server:
    image: ghcr.io/openuc2/project-docs:sha-cbad860
    volumes:
      - server-data:/data
      - server-config:/config
networks:
  default:
    name: none
    external: true
volumes:
  server-data: null
  server-config: null
