services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /docs /docs/
      caddy.handle: /docs/*
      caddy.handle.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy-ingress:
    external: true
