description: Support for integrating HTTP APIs and browser apps in a single path hierarchy
modifiers:
  - type: add-feature
    source: base/firewall
  - target: /deployments/infra/caddy-ingress.pkg
  - target: /deployments/infra/caddy-ingress.deploy.yml
  - target: /deployments/infra/device-portal.pkg
  - target: /deployments/infra/device-portal.deploy.yml
