#!/bin/bash -eu

device="$1"

while true; do
  if busctl call \
    org.freedesktop.UDisks2 /org/freedesktop/UDisks2/Manager \
    org.freedesktop.UDisks2.Manager GetBlockDevices \
    a{sv} 1 "auth.no_user_interaction" b TRUE |
    grep "/org/freedesktop/UDisks2/block_devices/$device"; then
    echo "UDisks2 is ready to mount block device $device!"
    break
  fi
  echo "Waiting for UDisks2 to finish identifying block device $device..."
  sleep 1
done
