services:
  server:
    image: ghcr.io/openuc2/device-admin:0.1.1-alpha.0@sha256:7ed5deac4fb4846b2ac9f4ee2c3c7d3bbb767812b754215f10bcbcc82e9b7817
    environment:
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
networks:
  default:
    name: none
    external: true
