services:
  server:
    image: ghcr.io/openuc2/device-admin:0.1.1-alpha.1@sha256:d5abad605e592f1f0d747d19a96090d255699df3adda4152eb0f3964c69201f7
    environment:
      - HTTP_BASEPATH=/admin/panel/
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
networks:
  default:
    name: none
    external: true
