services:
  server:
    image: ghcr.io/openuc2/device-admin:0.1.1-alpha.3@sha256:b2a6b6016c0cbf74d3a493ff080c9e8059ecdad9470b6656e9582e944763a302
    environment:
      - HTTP_BASEPATH=/admin/panel/
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
networks:
  default:
    name: none
    external: true
