services:
  server:
    image: ghcr.io/openuc2/device-admin:0.1.1-alpha.4@sha256:4a513f99572b03f3e3b8be402baad5fd0d51ea69e617224583a9db79b762f60a
    environment:
      - HTTP_BASEPATH=/admin/panel/
      - TEMPLATES_PATH=/web/templates
    volumes:
      - type: bind
        source: ./templates
        target: /web/templates
        read_only: true
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
networks:
  default:
    name: none
    external: true
