services:
  server:
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /admin/panel /admin/panel/
      caddy.handle_path: /admin/panel/*
      caddy.handle_path.reverse_proxy: "{{upstreams 3001}}"

networks:
  caddy-ingress:
    external: true
