services:
  server:
    networks:
      - caddy-ingress
    environment:
      - DOZZLE_BASE=/admin/dozzle
    labels:
      caddy: :80
      caddy.redir: /admin/dozzle /admin/dozzle/
      caddy.handle: /admin/dozzle/*
      caddy.handle.reverse_proxy: "{{upstreams 8080}}"

networks:
  caddy-ingress:
    external: true
