services:
  lepmonos:
    image: ghcr.io/desboe/lepmonos:arm64-latest@sha256:7636528ccc12b09613c2c4e96072e8f915ff12d561a32bebc83b033ce1c023f4
    privileged: true
    ports:
      - "3000:3000"
      - "8002:8002"
      - "8001:8001"
      - "8888:8888"
      - "2222:22"
    volumes:
      - /home/pi/:/config
      - /home/pi/:/dataset
      - /tmp:/tmp
      - /home/pi/LepmonOS:/home/pi/LepmonOS
    restart: always
