services:
  imswitch-noqt:
    image: ghcr.io/openuc2/imswitch-noqt:sha-39d3043@sha256:0677998ca61995a6cbbbe5459facedfa1a5a0a333666fe6589849661414b4f0a
    privileged: true
    ports:
      - "3000:3000"
      - "8002:8002"
      - "8001:8001"
      - "8888:8888"
      - "2222:22"
    volumes:
      - /home/pi/:/config
      - /home/pi/:/dataset
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /etc/machine-id:/etc/machine-id:ro
    environment:
      - HEADLESS=1
      - HTTP_PORT=8001
      - CONFIG_FILE=example_virtual_microscope.json
      - UPDATE_GIT=0
      - UPDATE_CONFIG=0
      - DATA_PATH=/dataset
      - CONFIG_PATH=/config
      - SCAN_EXT_DATA_FOLDER=1
      - EXT_DRIVE_MOUNT=/media
      - SSL=0
      - scan-ext-drive-mount=false
      - WIFI_MODE=host
    restart: always
