services:
  reverse-proxy-config:
    networks:
      - caddy-ingress
    labels:
      caddy: :80
      caddy.redir: /admin/cockpit /admin/cockpit/
      caddy.handle: /admin/cockpit/*
      caddy.handle.reverse_proxy: host.docker.internal:9090

networks:
  caddy-ingress:
    external: true
