name: check

on:
  push:
    branches:
      - main
      - edge
      - beta
      - stable
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - auto_merge_enabled  # needed for PRs opened via CI workflows without PATs
  merge_group:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        forklift-version: 
          - 0.8.0-beta.0
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Forklift
        uses: PlanktoScope/setup-forklift@v1
        with:
          version: ${{ matrix.forklift-version }}

      - name: Cache Forklift pallets
        run: |
          mkdir -p $HOME/.forklift
          forklift dev plt cache-plt
          forklift dev plt cache-dl

      - name: Run Forklift checks
        run: forklift dev plt check

      - name: Make Forklift deployment plan
        run: forklift dev plt plan
